theme: jekyll-theme-minimal
title: Daniel Paz
description: B.Sc Computer Science Student, with a rigor, creativity and passion for the world of programming and high-tech.
linkedin_url: https://www.linkedin.com/in/paz-daniel/
medium_url: https://medium.com/@danielpaz601
github_url: https://github.com/danielpaz6
gmail_url: mailto:danielpaz601@gmail.com
